### ISSUE TITLE
practica10

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipowar#1]
[PRACTICA_10_DIAGRAMA_DE_COMPONENTES (2).pdf](https://github.com/user-attachments/files/18070040/PRACTICA_10_DIAGRAMA_DE_COMPONENTES.2.pdf)

**Comment by HECTOR-KDM02** [comment]
30 puntos 


Todo se entrego en forma sin detalles nadamas mejorar la presentacion del documento poniendo los espacios donde es debido para separar los apartados y una mejor presentacion

**Comment by josealfredo79** [comment]
esto no es...favor de checar...es diagrama de componentes. por favor...

**Comment by ArcangelGC** [comment]
CORREGIDO

**Comment by josealfredo79** [comment]
Revisado..
